{% set name = "cctk" %}
{% set version = "0.2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67400b694914f5a70c0540b3948e024ade15030f70a96c1e0e420322c6842a16

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - basis_set_exchange
    - importlib_resources
    - networkx
    - numpy
    - pyahocorasick
    - python >=3.6
    - pyyaml
    - scipy

test:
  imports:
    - cctk
    - cctk.data
    - cctk.groups
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ekwan/cctk
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: computational chemistry toolkit
  doc_url: https://cctk.readthedocs.io
  dev_url: https://github.com/ekwan/cctk

extra:
  recipe-maintainers:
    - corinwagen
