{% set name = "cctk" %}
{% set version = "0.2.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 874bdd2c7f66a949eea6b063a56b92fddba3bad5e3b87577bf2fb9ddae02b52c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - basis_set_exchange
    - importlib_resources
    - networkx
    - numpy
    - pyahocorasick
    - python >=3.6
    - pyyaml
    - scipy

test:
  imports:
    - cctk
    - cctk.data
    - cctk.groups
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ekwan/cctk
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: computational chemistry toolkit
  doc_url: https://cctk.readthedocs.io
  dev_url: https://github.com/ekwan/cctk

extra:
  recipe-maintainers:
    - corinwagen
